name: Build with Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout nuttx code
        uses: actions/checkout@v4
        with:
          repository: apache/nuttx
          ref: master
          path: sources/nuttx
          fetch-depth: 1

      - name: Checkout nuttx-apps code
        uses: actions/checkout@v4
        with:
          repository: apache/nuttx-apps
          ref: master
          path: sources/apps
          fetch-depth: 1
          
      - name: Docker Pull
        run: docker pull ghcr.io/apache/nuttx/apache-nuttx-ci-linux

      - name: List docker image
        run: |
          docker image ls
