name: Build and Test with local setup environment

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: build
        run: |
          pwd
          touch build.txt
      - name:  Upload a Build Artifact2
        uses: actions/upload-artifact@v4.3.3
        with:
          name: build_output
          path: build.txt

  test_wamr_other_bin:
    name: start test other bin
    runs-on: [self-hosted, wasm-other-bin]
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build_output

      - name: Flash other bin
        run: |
          pwd
          zip -r report.zip flash_images/*

      - name: Upload test report
        uses: actions/upload-artifact@v4.3.3
        with:
          name: test_finish
          path: |
            report.zip

  test_wamr_wasi_bin:
    name: start test wasi bin
    runs-on: [self-hosted, wasm-wasi-bin]
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build_output

      - name: Flash wasi bin
        run: |
          pwd
          zip -r report-wasi.zip flash_images/*

      - name: Upload test report
        uses: actions/upload-artifact@v4.3.3
        with:
          name: test_finish
          path: |
            report-wasi.zip
