name: Upload and Download from Alibaba Cloud OSS

on:
  push:
    branches:
      - main

jobs:
  oss-operations:
    # 修改为自托管运行器的标签，这里假设标签为 self-hosted
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 上传文件到阿里云 OSS
      - name: Upload to OSS
        uses: aliyun/aliyun-oss-upload-action@v1
        with:
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          endpoint: ${{ secrets.ALIYUN_OSS_ENDPOINT }}
          bucket: ${{ secrets.ALIYUN_OSS_BUCKET }}
          source: ./path/to/local/file  # 替换为要上传的本地文件路径
          target: /path/in/oss/  # 替换为 OSS 目标路径

      # 从阿里云 OSS 下载文件
      - name: Download from OSS
        uses: aliyun/aliyun-oss-download-action@v1
        with:
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          endpoint: ${{ secrets.ALIYUN_OSS_ENDPOINT }}
          bucket: ${{ secrets.ALIYUN_OSS_BUCKET }}
          source: /path/in/oss/file  # 替换为 OSS 中要下载的文件路径
          target: ./path/to/local/directory  # 替换为本地目标目录
